### ISSUE TITLE
[FE] 필터 기능 리스트 API 요청

### ISSUE THREAD

**Issue by 96limshyun** [codesquad-masters2024-team07/issue-tracker#7]
## 어떤 기능인가요?
- 필터를 누르면 상세 리스트가 보여진다.
- 각 상세 필터를 누르면 input 창에 쿼리가 추가 되고 추가된 쿼리를 취합해 API 요청을 보낸다.

> 추가하려는 기능에 대해 간결하게 설명해주세요
 - 담당자, 레이블, 마일스톤, 작성자 필터 데이터 API 요청
 - 해당 필터를 클릭했을때 검색창에 추가할 쿼리

## 상세 내용
https://github.com/codesquad-masters2024-team07/issue-tracker/assets/126482821/15ebbc7c-7424-4762-a9fa-8de01095b4e1

- 위 영상과 같이  담당자, 레이블, 마일스톤, 작성자 필터의 데이터가 없어 그릴 수가 없습니다. 어떤 데이터를 요청하면 되는지 정해야 할것 같습니다.
- 이슈 필터를 누르면 영상처럼 검색창에 쿼리가 생성되는데, 담당자, 레이블, 마일스톤, 작성자 상세 필터를 누르면 어떤 쿼리를 보낼지도 정해야 할 것 같습니다.

## 작업 상세 내용

- [X] filterUI 컴포넌트 구현 
- [X] input, filter: reducer로 연결하여 공통 컴포넌트로 구현
- [ ] 담당자, 레이블, 마일스톤, 작성자 필터 데이터 요청
- [ ] 검색창에 생성된 쿼리를 취합해 인코딩한 쿼리를 API요청 후 데이터 렌더

**Comment by hiidy** [comment]
dfdfd
